apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    name: backend-svc
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: backend-port
  selector:
    name: backend