apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: kylinhuang/hello_world_frontend:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
          name: tw-http        
        resources:
          requests:
            cpu: 125m